version: "3.2"

services:
    db_node:
        container_name: db_node
        image: cockroachdb/cockroach:latest
        volumes:
            - ./data/db_node:/cockroach/cockroach-data
        command: start-single-node --insecure
        ports:
            - "26257:26257"
            - "8080:8080"
            
    api_node:
        build: ./api
        ports:
            - "8001:8001"
        environment:
            - DATABASE_URL=postgresql://root@db_node:26257/defaultdb?sslmode=disable
            - PORT=8001
        depends_on:
            db_node:
                condition: service_started

networks:
    default:
        driver: bridge